org.gradle.jvmargs=-Xmx2048M
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
loom.ignoreDependencyLoomVersionValidation=true

enabled_platforms=fabric,neoforge

mod_id=exposure_camcorder
archives_name=exposure_camcorder
mod_name=Exposure Camcorder
mod_version=0.1.0
mod_license=MIT
maven_group=io.github.exposure_camcorder
mod_authors=Doona
mod_description=Dynamic Photograph extension mod for Exposure.
mod_page=https://github.com/doona2026/ExposureCamcorder
mod_issues=https://github.com/doona2026/ExposureCamcorder/issues

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
parchment_version=1.21.1:2024.11.17

fabric_loader_version=0.16.9
fabric_api_version=0.102.1+1.21.1

neoforge_version=21.1.200
neoforge_version_range=[21,)
neoforge_loader_version_range=[4,)

forge_config_api_port_version=21.1.0
jupiterVersion=5.11.3

exposure_group=io.github.mortuusars.exposure
exposure_version=1.9.16
