org.gradle.jvmargs=-Xmx2048M
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
loom.ignoreDependencyLoomVersionValidation=true

enabled_platforms=fabric,forge

mod_id=exposure_camcorder
archives_name=exposure_camcorder
mod_name=Exposure Camcorder
mod_version=0.1.0
mod_license=MIT
maven_group=io.github.exposure_camcorder
mod_authors=Doona
mod_description=Dynamic Photograph extension mod for Exposure.
mod_page=https://github.com/example/exposure-camcorder
mod_issues=https://github.com/example/exposure-camcorder/issues

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
parchment_version=1.20.1:2023.09.03

fabric_loader_version=0.16.10
fabric_api_version=0.92.11+1.20.1

forge_version=47.4.10
forge_version_range=[47,48)
forge_loader_version_range=[47,48)

forge_config_api_port_version=8.0.1
jupiterVersion=5.11.3

exposure_group=io.github.mortuusars.exposure
exposure_version=1.9.20
